### ISSUE TITLE
[Feature request] Continuous integration support

### ISSUE THREAD

**Issue by Kristinita** [regebro/pyroma#15]
### 1. Request

It would be nice, if pyroma will support continuous integration services as [**Travis CI**](https://travis-ci.org/) and [**AppVeyor**](https://www.appveyor.com/).

### 2. Argumentation

Error reporting in `setup.py` and/or `setup.cfg` in continuous integration process.

### 3. Example

my example `.travis-yml` file:

```yaml
language: python
python:
  - "3.6.4"
install:
  - pip install pyroma
script:
  - pyroma .
```

**If** `Final rating: 10/10`:

    build passed.

**else**:

    build failed.

Thanks.
